// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"

	// EdgePersonas holds the string denoting the personas edge name in mutations.
	EdgePersonas = "personas"

	// PersonasInverseLabel holds the string label denoting the personas inverse edge type in the database.
	PersonasInverseLabel = "persona_gender_is"
)

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)
