// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value", Type: field.TypeString},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:        "genders",
		Columns:     GendersColumns,
		PrimaryKey:  []*schema.Column{GendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PersonasColumns holds the columns for the "personas" table.
	PersonasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "gender", Type: field.TypeString, Default: "unknown"},
	}
	// PersonasTable holds the schema information for the "personas" table.
	PersonasTable = &schema.Table{
		Name:        "personas",
		Columns:     PersonasColumns,
		PrimaryKey:  []*schema.Column{PersonasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PersonaGenderIsColumns holds the columns for the "persona_genderIs" table.
	PersonaGenderIsColumns = []*schema.Column{
		{Name: "persona_id", Type: field.TypeInt},
		{Name: "gender_id", Type: field.TypeInt},
	}
	// PersonaGenderIsTable holds the schema information for the "persona_genderIs" table.
	PersonaGenderIsTable = &schema.Table{
		Name:       "persona_genderIs",
		Columns:    PersonaGenderIsColumns,
		PrimaryKey: []*schema.Column{PersonaGenderIsColumns[0], PersonaGenderIsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "persona_genderIs_persona_id",
				Columns: []*schema.Column{PersonaGenderIsColumns[0]},

				RefColumns: []*schema.Column{PersonasColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "persona_genderIs_gender_id",
				Columns: []*schema.Column{PersonaGenderIsColumns[1]},

				RefColumns: []*schema.Column{GendersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GendersTable,
		PersonasTable,
		PersonaGenderIsTable,
	}
)

func init() {
	PersonaGenderIsTable.ForeignKeys[0].RefTable = PersonasTable
	PersonaGenderIsTable.ForeignKeys[1].RefTable = GendersTable
}
