// Code generated by entc, DO NOT EDIT.

package persona

const (
	// Label holds the string label denoting the persona type in the database.
	Label = "persona"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"

	// EdgeGenderIs holds the string denoting the genderis edge name in mutations.
	EdgeGenderIs = "genderIs"

	// GenderIsLabel holds the string label denoting the genderis edge type in the database.
	GenderIsLabel = "persona_gender_is"
)

var (
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
	// DefaultGender holds the default value on creation for the gender field.
	DefaultGender string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)
