// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/gremlin/graph/dsl"
)

// Gender is the predicate function for gender builders.
type Gender func(*dsl.Traversal)

// Persona is the predicate function for persona builders.
type Persona func(*dsl.Traversal)
